# Routing automático a nivel de protocolo PipeWire / PulseAudio:
# Todo flujo de reproducción se procesa a través del filtro maestro hifi-loss
pulse.rules = [
    {
        matches = [
            {
                media.class = "Stream/Output/Audio"
                node.name   = "!~hifi_loss.*"
            }
        ]
        actions = {
            update-props = {
                target.object = "hifi_loss_sink"
            }
        }
    }
]
